# SDK log level (off | info | debug | trace)
sdk_log_level: "${SDK_LOG_LEVEL}"

# Properties for the Platform
platform:
  task_source_name: 

# Properties for the Kinetic Request CE Source
ce:
  server: "http://request-ce:8080/kinetic"
  system_credentials:
    username: "admin"
    password: "admin"
  space_admin_credentials:
    username: "${SPACE_USER_USERNAME}"
    password: "${SPACE_USER_PASSWORD}"
  space_integration_credentials:
    username: "integration.user"
    display_name: "Integration User"
  task_source_name: "Kinetic Request CE"
  filestore:
    type: "Local"
    directory: "/home/filesDirectory"

# Properties for Kinetic Task
task:
  server: "http://task:8080/kinetic-task"
  credentials:
    username: "admin"
    password: "admin"
  oauth:
    endpoint_server: "${TASK_OAUTH_ENDPOINT_SERVER}"
    redirect_endpoint_server: "${TASK_OAUTH_REDIRECT_ENDPOINT_SERVER}"

# Properties for Kinetic Bridgehub
bridgehub:
  server: "http://bridgehub:8080/kinetic-bridgehub"
  credentials:
    username: "admin"
    password: "admin"

# Properties for Kinetic Filehub
filehub:
  server: "http://filehub:8080/kinetic-filehub"
  credentials:
    username: "admin"
    password: "admin"

# Kinetic Data SMTP Info (Set on SMTP Handler)
smtp:
  server: "mailer"
  port: "587"
  tls: "true"
  username: ""
  password: ""

# Kinetic Task kinetic_request_ce_notification_template_send_v1 handler
notification_template_handler:
  smtp_server: "mailer"
  smtp_port: "587"
  smtp_tls: "true"
  smtp_username: ""
  smtp_password: ""
  smtp_from_address: "no-reply"
